import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./main.module.css";
import { PrimaryLink } from "./primaryLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.menu}>
          <h1>Like Native</h1>
          <PrimaryLink href="/" text={"Dashboard"}/>
          <PrimaryLink href="/practice" text={"Practice"}/>
          <PrimaryLink href="/test" text={"Test"}/>
        </div>
        {children}
      </body>
    </html>
  );
}
